[greeter]
background=#08090c
theme-name=Adwaita-dark
icon-theme-name=Adwaita
font-name=Sans 11
logo=/usr/share/ricos/ricos-logo.png
indicators=~host;~spacer;~clock;~spacer;~session;~power
clock-format=%H:%M
